/** Automatically generated by the project's tsgen/TSExportGenerator.csproj for JSExport decorated members. */
export module dotnetEx {
	export interface VoxelML {
		Engine: {
			CreateGeometry(): Promise<void>;
		};
		Binary: {
			
		/**
		 * 
		 * Unpacks binary data to a typed structure.
		 * 
		 * @param data Expects structured data, a type must be in the 4 byte header.
		 * @returns true if successfully unpacked to a managed type
		 */
			Unpack(data: Uint8Array): boolean;
		};
	}

	const VoxelML: VoxelML;
}

export type dotnetExports = typeof dotnetEx;
